spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=YOUR_DB_USER
spring.datasource.password=YOUR_DB_PASSWORD

jwt.secret=YOUR_BASE64_SECRET_HERE
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD