spring.application.name=Event-Management-Platform

spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=YOUR_DB_USER
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.persist-authorization=false

jwt.secret=YOUR_BASE64_SECRET_HERE
jwt.expiration=86400000

app.admin.email=YOUR_ADMIN_EMAIL
app.admin.password=YOUR_ADMIN_PASSWORD
app.organizer.email=YOUR_ORGANIZER_EMAIL
app.organizer.password=YOUR_ORGANIZER_PASSWORD
app.user.email=YOUR_USER_EMAIL
app.user.password=YOUR_USER_PASSWORD